### ISSUE TITLE
Mod compatibility?

### ISSUE THREAD

**Issue by rubyFeedback** [Argent77/A7-SkipChateauIrenicus#1]
Is this MOD incompatible to other MODS? Perhaps the main README could
keep such an entry.

Specifically there is another MOD where the female NPC that accompanies
the main actor begins to talk about the original hideout in baldur's gate 1.

There a side quest is opened and some unique abilities are granted by
Gorion or so. You have to go through some library or you can skip it.

Does Skip Chateua Irenicus cancel that? I'd want to have the unique
abilities from that MOD. But also skip the initial dungeon as I just
want to test some other MODs so the first dungeon is rather tedious.
I speed run it usually but it still takes me about 10 minutes or so
including all loot.

**Comment by Argent77** [comment]
There is a [compatibility section](https://argent77.github.io/A7-SkipChateauIrenicus/index.html#compatibility) in the readme.

I haven't played the mod you mentioned, but the shortcut provided by this mod is on voluntary basis. You are free to decide at anytime to use it or not while you're in the dungeon. Apart from that, this mod only makes very few modifications to the opening dungeon. Unless the other mod specifically modifies the one script that is crucial for this mod to work it should be compatible.

Did you test whether the mod in question works as intended?
