### ISSUE TITLE
I think there is something wrong in between SkipChateauIrenicus and weidu

### ISSUE THREAD

**Issue by rubyFeedback** [Argent77/A7-SkipChateauIrenicus#2]
So first off, this is my current mod order - I skip extended planar sphere and tactics remix as these are not well designed.

    Ascension                                        # 01, Testing this since October 2023. Must come before wheels of prophecy.
    jans-alchemy                                     # 48
    BridgesBlock                                     # 03
    The_Sellswords                                   # 02
    The_White_Queen                                  # 04, should come after Tales of the Deep Garden.
    Tales_of_the_Deep_Gardens                        # 05
    Tower_of_Deception                               # 06
    The_Dreadful_Tales_In_Love_Undeath               # 07
    The_Dreadful_Tales_Juniper_and_the_Stone_Leech   # 08
    of_heirlooms_and_classes-v2.1-02.12.2023         # 11 new items
    Dusk_Aldant                                      # 10, may be better to install it fairly late.
    Trials_of_the_Luremaster_mod                     # 11
    Back_to_Brynnlaw                                 # 12
    Assassinations                                   # 13
    Southern_Edge                                    # 14
    The_Ooze_Lounge                                  # 15
    Tangled_Oak_Isle                                 # 16
    lucy-the-wyvern                                  # 17
    navarra                                          # 18
    Eilistraee                                       # 19
    Fishing_for_Trouble                              # 20
    Reunion_mod                                      # 22
    Sirene-NPC                                       # 23
    Alabaster_Sands                                  # 24
    Tales_of_Anegh                                   # 25, for chapter 6 and beyond
    Ascalons-questpack                               # 26
    Ariena                                           # 28, another NPC
    The_journey_to_the_Whin_Hill                     # 29
    Pai-Na-NPC-mod-for-BG2-EE-1.8a                   # 30, another NPC mod
    willowisp                                        # 31
    Every_mod_and_dog                                # 32
    Drizzt-RoTerror-EE                               # 33
    Romantic_Encounters                              # 34
    BloodiedStingsOfBarovia                          # 35
    Skie_the_cost_of_one_girl-5.2                    # 36
    Fade_v5.6                                        # 37
    Wings-1.05                                       # 38, wings mod for aerie
    Unfinished_Business                              # 39; Should come late, but before cliffkey. Contains Artemis Entreri and the kidnapping of Boo.
    Unofficial_Item_Pack                             # 40, a great mod.
    forgotten-armament                               # 41
    Quest_Pack                                       # 42 Should come after "Unfinished Business".
    sod2bg2_iu-v2.0.6                                # 43; should come late
    ItemUpgrade                                      # 44
    Dvaradime                                        # some NPC
    Made_in_Heaven_mod                               # 45
    Archery-v4_02.12.2023                            # 48, a new mod to try
    Homeward_Bound                                   # 46
    heart_of_the_wood                                # 47, an item
    Walahnan_BG2-v1.00                               # 49
    Tatoos-02.12.2023                                # Tatoos mod
    Mystigan                                         # 51, a NPC
    Skitia-NPCs                                      # 52
    Check_the_Bodies                                 # 53; also installs the Saerk Farrahd's banquet invitation. This one crashed the game in September 2023, so I moved this mod downwards.
    I_Shall_Never_Forget                             # 55, by Lava, should come late as it adds new areas
    wheels                                           # 56, Wheels of Prophecy
    Lhannd                                           # 58, a NPC but it also installs new areas.
    saradas-magic-for-BG2                            # 50, a new NPC
    Skip_Chateau_Irenicus                            # 57; should come late
    Isra_NPC                                         # 27
    Innershade                                       # 00, should come fairly late as it modifies maps
    Heroes_Thieves_and_Moneylenders                  # ~61, should come late as it changes the map. For now I won't install it, perhaps at a later time again.
    Tweaks_Anthology                                 # 60; should come last
    worldmap-mod-v12.0.0                             # 61 or this should come last ...                

Please ignore the parts after the '#' comments; I update these manually, and first I shuffle
the order, then I update the '#', so the numbering there is incorrect.

Anyway. I installed skip chateau ireniucs, about 5th last mod. And when I click on 
its installation, weidu.exe keeps on saying it is updating THE VERY NEXT MOD that
is installed. Meaning, skip chateau installs fine, but then any next mod that is to
be installed, lags, and weidu shows this problem at skip chateau irenicus which
kind of hangs. After several minutes of not doing anything past this point, I
kill the window, and re-try, with the same result. Oddly enough after a few more
tries I can then install another mod. But then the very next mod hangs AGAIN.

This happens almost only with skip chateau ireniucs. It does happen with a few
other mod, but skip chateua irenicus is now what I see being the biggest 
troublemaker in regards to weidu. No idea why weidu acts that way, but perhaps
skip chateau is doing something that confuses weidu. Anyway, I just report it
here - perhaps someone can find out why weidu hangs at the past-skip-chateau
installation part. I actually need that mod these days because the first chapter
is super-boring and tedious.

**Comment by Argent77** [comment]
I doubt it has anything to do with the mod itself. Actual mod content shouldn't be processed at that point yet. It's more likely caused by WeiDU's auto-update mechanism. When both 32-bit and 64-bit versions of the WeiDU executable are present then the update process seems to require more time for some reason. It probably adds up if many WeiDU binaries are to be checked that way.

You could replace `setup-SkipChateauIrenicus.exe` by a copy of the setup installer of another mod that is built for another architecture (check the file sizes) and see if it helps.
